#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run Gitleaks protect on staged changes
# The hook will prevent commit if a secret is detected.
# Skip if gitleaks is not installed
if command -v gitleaks &> /dev/null; then
  gitleaks protect --staged
fi
